# Generated by Django 4.2.30 on 2026-09-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_agriculturalzone_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='for_sale',
            field=models.BooleanField(default=False, verbose_name='À vendre'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix de vente'),
        ),
    ]
