# Generated by Django 4.2.30 on 2026-09-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN Mobile Money'), ('MOOV', 'Moov Money'), ('CARD', 'Carte bancaire')], max_length=20, null=True),
        ),
    ]
