# Generated by Django 4.2.30 on 2026-09-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_purchase_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='transfer_validated',
            field=models.BooleanField(default=False, verbose_name='Transfert de propriété validé'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transfer_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation du transfert'),
        ),
    ]
