# Generated by Django 4.2.30 on 2026-09-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_purchase_transfer_validated_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('parcel', 'buyer'), name='unique_purchase_per_parcel_buyer'),
        ),
    ]
