# Generated by Django 4.2.30 on 2026-09-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_purchase_unique_purchase_per_parcel_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='sale_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Réservée - paiement effectué'), ('SOLD', 'Vendue')], default='AVAILABLE', max_length=20, verbose_name='État de la vente'),
        ),
    ]
